version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"
